--CONSULTAS 3
-- Histórico de compras por cliente(año, nombre del cliente, cantidad de paquetes comprados y qtotal de pago).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO ) AS AñO,NOMBRE_C,SUM(CANTIDAD_PT) AS
CANTIDAD_PAQUETES_COMPRADOS,SUM(TOTAL_PAGO) AS TOTA_PAGO
FROM PAQUETE_TURISTICO
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE 
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
INNER JOIN PAGO ON CONTRATACION.ID_CONTRATACION =PAGO.ID_CONTRATACION
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO ),NOMBRE_C ORDER BY EXTRACT (YEAR FROM FECHA_PAGO ) DESC;