
--CONSULTA 1
--Histórico de paquetes vendido por cada agente (año, nombre del agente, el tipo y la cantidad de paquetes vendidos).
SELECT 
EXTRACT(YEAR FROM FECHA_PAGO) AS AñO,NOMBRE_A AS NOMBRE_AGENTE,TIPO_PT,sum(CANTIDAD_PT) as Cantidad_Vendidos FROM CONTRATACION
INNER JOIN AGENTE ON CONTRATACION.ID_AGENTE=AGENTE.ID_AGENTE
INNER JOIN PAQUETE_TURISTICO ON AGENTE.ID_AGENTE=PAQUETE_TURISTICO.ID_AGENTE 
GROUP BY EXTRACT(YEAR FROM FECHA_PAGO),NOMBRE_A ,TIPO_PT order by EXTRACT(YEAR FROM FECHA_PAGO) desc