
--CONSULTA 2
-- Histórico de locales por paquetes ordenados de mayor a menor (año, lugar y cuantos paquetes obtuvo).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO) AS AñO ,TIPO_EMPRESA AS LUGAR,SUM(CANTIDAD_PT) AS CANTIDAD FROM CONVENIOS
INNER JOIN PAQUETE_TURISTICO ON CONVENIOS.ID_CONVENIOS= PAQUETE_TURISTICO.ID_CONVENIOS
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO),TIPO_EMPRESA
ORDER BY SUM(CANTIDAD_PT)  DESC;