--CONSULTA 4
--Histórico de satisfacciones de Empresas con convenios. (año, lugar, nombre del cliente, total de Visitas).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO) AS AñO,TIPO_EMPRESA AS LUGAR,NOMBRE_C AS NOMBRE_CLIENTE,
SUM(TOTAL_VISITAS)AS TOTAL_VISITAS,SUM(BUENAS_VISITAS)AS BUENAS_VISITAS,SUM(MALAS_VISITAS) AS MALAS_VISITAS FROM SASTIFACCION
INNER JOIN CLIENTE ON SASTIFACCION.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CONTRATACION.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN PAQUETE_TURISTICO ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONVENIOS ON PAQUETE_TURISTICO.ID_CONVENIOS=CONVENIOS.ID_CONVENIOS
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO),TIPO_EMPRESA ,NOMBRE_C ORDER BY EXTRACT (YEAR FROM FECHA_PAGO) DESC;