
--CONSULTAS

--Histórico de paquetes vendido por cada agente (año, nombre del agente, el tipo y la cantidad de paquetes vendidos).
SELECT 
EXTRACT(YEAR FROM FECHA_PAGO) AS AñO,NOMBRE_A AS NOMBRE_AGENTE,TIPO_PT,sum(CANTIDAD_PT) as Cantidad_Vendidos FROM CONTRATACION
INNER JOIN AGENTE ON CONTRATACION.ID_AGENTE=AGENTE.ID_AGENTE
INNER JOIN PAQUETE_TURISTICO ON AGENTE.ID_AGENTE=PAQUETE_TURISTICO.ID_AGENTE 
GROUP BY EXTRACT(YEAR FROM FECHA_PAGO),NOMBRE_A ,TIPO_PT order by EXTRACT(YEAR FROM FECHA_PAGO) desc

-- Histórico de locales por paquetes ordenados de mayor a menor (año, lugar y cuantos paquetes obtuvo).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO) AS AñO ,TIPO_EMPRESA AS LUGAR,SUM(CANTIDAD_PT) AS CANTIDAD FROM CONVENIOS
INNER JOIN PAQUETE_TURISTICO ON CONVENIOS.ID_CONVENIOS= PAQUETE_TURISTICO.ID_CONVENIOS
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO),TIPO_EMPRESA
ORDER BY SUM(CANTIDAD_PT)  DESC;

--CONSULTAS 3
-- Histórico de compras por cliente(año, nombre del cliente, cantidad de paquetes comprados y qtotal de pago).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO ) AS AñO,NOMBRE_C,SUM(CANTIDAD_PT) AS
CANTIDAD_PAQUETES_COMPRADOS,SUM(TOTAL_PAGO) AS TOTA_PAGO
FROM PAQUETE_TURISTICO
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE 
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
INNER JOIN PAGO ON CONTRATACION.ID_CONTRATACION =PAGO.ID_CONTRATACION
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO ),NOMBRE_C ORDER BY EXTRACT (YEAR FROM FECHA_PAGO ) DESC;

--CONSULTA 4
--Histórico de satisfacciones de Empresas con convenios. (año, lugar, nombre del cliente, total de Visitas).
SELECT 
EXTRACT (YEAR FROM FECHA_PAGO) AS AñO,TIPO_EMPRESA AS LUGAR,NOMBRE_C AS NOMBRE_CLIENTE,
SUM(TOTAL_VISITAS)AS TOTAL_VISITAS,SUM(BUENAS_VISITAS)AS BUENAS_VISITAS,SUM(MALAS_VISITAS) AS MALAS_VISITAS FROM SASTIFACCION
INNER JOIN CLIENTE ON SASTIFACCION.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CONTRATACION.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN PAQUETE_TURISTICO ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONVENIOS ON PAQUETE_TURISTICO.ID_CONVENIOS=CONVENIOS.ID_CONVENIOS
GROUP BY EXTRACT (YEAR FROM FECHA_PAGO),TIPO_EMPRESA ,NOMBRE_C ORDER BY EXTRACT (YEAR FROM FECHA_PAGO) DESC;
