--CONSULTAS

--Histórico de paquetes vendido por cada agente (año, nombre del agente, el tipo y la cantidad de paquetes vendidos).
SELECT 
FECHA_PAGO AS AñO,NOMBRE_A AS NOMBRE_AGENTE,TIPO_PT,CANTIDAD_PT FROM CONTRATACION
INNER JOIN AGENTE ON CONTRATACION.ID_AGENTE=AGENTE.ID_AGENTE
INNER JOIN PAQUETE_TURISTICO ON AGENTE.ID_AGENTE=PAQUETE_TURISTICO.ID_AGENTE

-- Histórico de locales por paquetes ordenados de mayor a menor (año, lugar y cuantos paquetes obtuvo).
SELECT FECHA_PAGO AS AñO ,TIPO_EMPRESA AS LUGAR,CANTIDAD_PT AS CANTIDAD FROM CONVENIOS
INNER JOIN PAQUETE_TURISTICO ON CONVENIOS.ID_CONVENIOS= PAQUETE_TURISTICO.ID_CONVENIOS
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
ORDER BY CANTIDAD_PT DESC;

-- Histórico de compras por cliente(año, nombre del cliente, cantidad de paquetes comprados y qtotal de pago).
SELECT FECHA_PAGO AS AñO,NOMBRE_C,CANTIDAD_PT AS CANTIDAD_PAQUETES_COMPRADOS,TOTAL_PAGO FROM PAQUETE_TURISTICO
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE 
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
INNER JOIN PAGO ON CONTRATACION.ID_CONTRATACION =PAGO.ID_CONTRATACION;

--Histórico de satisfacciones de Empresas con convenios. (año, lugar, nombre del cliente, total de Visitas).
SELECT 
FECHA_PAGO AS AñO,TIPO_EMPRESA AS LUGAR,NOMBRE_C,TOTAL_VISITAS,BUENAS_VISITAS,MALAS_VISITAS FROM SASTIFACCION
INNER JOIN CONVENIOS ON CONVENIOS.ID_SASTIFACION = SASTIFACCION.ID_SASTIFACION
INNER JOIN PAQUETE_TURISTICO ON CONVENIOS.ID_CONVENIOS=PAQUETE_TURISTICO.ID_CONVENIOS
INNER JOIN CLIENTE ON PAQUETE_TURISTICO.ID_CLIENTE=CLIENTE.ID_CLIENTE
INNER JOIN CONTRATACION ON CLIENTE.ID_CLIENTE=CONTRATACION.ID_CLIENTE
